# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO   
    com.proactivity.rmq: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: 
    name: @base.logs.path@

server:
  port : 8082
  servlet:
    contextPath: /proactivity-rmq-producer
    
spring:
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
  main:
    allow-bean-definition-overriding: true
    jackson.serialization.FAIL_ON_EMPTY_BEANS: false
    profiles.active: @activatedProperties@

    
send:
  to:
    aci:
      exchange: send.to.aci.exchange
      routingkey: send.to.aci.routingkey
      queue: send.to.aci.queue
    erica:
      exchange: send.to.erica.exchange
      routingkey: send.to.erica.routingkey
      queue: send.to.erica.queue
