

CREATE TABLE EMPLOYEE (
   EMPLOYEE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   NAME varchar(100),
   LAST_NAME varchar(100),   
   PRIMARY KEY (EMPLOYEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;