
version: "3.0"
services:
  proactivity-rmq-producer:
    build: .
    restart: always
    image: proactivity-rmq-producer:1.0
    container_name: proactivity-rmq-producer
    ports:
      - 8082:8082
    networks:
      - proactivity-rmq-producer-net
    environment:
      - spring.rabbitmq.host=172.25.0.1
      - spring.rabbitmq.port=5673
      
    volumes:
      - /home/davide/proactivity-rmq-producer/logs:/logs  
    
networks:
  proactivity-rmq-producer-net:
    name: proactivity-rmq-producer-net
    driver: bridge
