

CREATE TABLE DECISION_CASE (
   DECISION_CASE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   CATEGORY VARCHAR(20),
   CONTEXT VARCHAR(100),
   JAVA_CLASS_NAME VARCHAR(500),
   JSON_PATH VARCHAR(300),  
   JSON_TYPE VARCHAR(20),    
   SEARCH_VALUE VARCHAR(100),
   SEARCH_VALUE_TYPE VARCHAR(100),
   ENABLED BIT(1) NOT NULL DEFAULT b'1',
   PRIMARY KEY (DECISION_CASE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE DECISION_CASE_RULE(
    DECISION_CASE_RULE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    RULE_FILE VARCHAR(500) NOT null,
    SEARCH_KEY VARCHAR(50),
    ORDER INT,
    EXIT_ON_FAILURE BIT(1),
    EXIT_ON_SUCCESS BIT(1),
    ENABLED BIT(1) NOT NULL DEFAULT b'1',
    DECISION_CASE_ID BIGINT(20),
    PRIMARY KEY (DECISION_CASE_RULE_ID),
    CONSTRAINT DECISION_CASE_FK FOREIGN KEY (DECISION_CASE_ID) REFERENCES DECISION_CASE (DECISION_CASE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;