
version: "3.0"
services:

  mysqldb:
    image: "mysql:8.0.34"
    restart: always
    ports:
      - 3306:3306
    networks:
      mysql-server-net:
        ipv4_address: 172.27.0.2
    environment:
      MYSQL_DATABASE: people
      MYSQL_ROOT_PASSWORD: root

networks:
  mysql-server-net:
    name: mysql-server-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
